### ISSUE TITLE
Needs better tutorial

### ISSUE THREAD

**Issue by chiburawk** [Cities2Modding/MOOB#1]
1. It's not clear where "Load Heightmap" button can be found in Map Editor. Better specify this in the README
2. It's also not clear that the mod itself doesn't provide access to the Map Editor
3. It's also very not clear that the Heightmaps files should be located in the Screenshots folder for some reason?
4. And alas it's also not clear why any of my heightmaps aren't working. I use the same site that I used for CS 1 heightmaps (heightmap skydark pl) but after choosing desired heightmap and clicking "Load" button under "Import heightmaps" menu nothing happens beside texture loading. It's unclear whether I'm doing something wrong or the mod's not working

Tutorial and better README would be much appreciated!

**Comment by optimus-code** [comment]
I have no idea where you got this impression but none of this is true of the mod. It sounds like you've not gotten the mod to load properly, please ensure you are using BepInEx v5. As it does in fact enable access to the map editor, it does not require files to be in the screenshots folder it will open a file browse dialog when you click import. What you explained is the default functionality without the mod loaded.

Readme is plenty good enough if you follow it.

**Comment by amazingoomoo** [comment]
My mod and bepinex is installed fine, the Editor button is appearing on my main menu, but I cannot for the life of me work out how to import a heightmap into the editor, or even how to save my map when I'm done. I think this is broken.

**Comment by Morkeoth** [comment]
I have the exact same problems.
I cannot import or export anything. The buttons for doing that in the shovel icon menu doesn't work properly.
And when i click on save or load nothing happens.

**Comment by ZooHuba** [comment]
I believe I got bepinex to work correctly too. Says mod is loaded but still no dialog pops up when selecting load heightmap. I have to put png. File into games heightmaps folder but still another error occurs when loading maps and crashes.

**Comment by optimus-code** [comment]
Importing heightmaps is no longer current MOOB functionality. Any issues with this are game related and liable to be fixed with official game updates soon.
