### ISSUE TITLE
How do i import a Height map?

### ISSUE THREAD

**Issue by Theo965** [Cities2Modding/MOOB#15]
So i install the MOOB mod, i go into the editor, i press import height map and no height maps show up? How do i fix this?

**Comment by BrokVid** [comment]
Нужно положить по пути
C:\Users\YOUR_USER\AppData\LocalLow\Colossal Order\Cities Skylines II\Heightmaps

Но тут другой нюанс, всем известный сайт в бета версии вываливает тупо черную карту высот, а в старой версии карту высот с неподходящими размерами, а как написано в описании мода - функция коррекции этих размеров устарела. че делать хз, ждать обновлений видимо

**Comment by Theo965** [comment]
Thank you.
I could'nt find the folder, so i created one myself and it worked.
