### ISSUE TITLE
Issues with heightmap importing

### ISSUE THREAD

**Issue by WatchfulRelic91** [Cities2Modding/MOOB#3]
When attempting to import a RAW heightmap, I get the following error message: 

> Load16BitRaw failed: The size of the RAW file does not match the specified dimensions.
> Colossal.Logging.CustomLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogError(Object)
> MOOB.Extensions.Texture2DExtensions:Load16BitRaw(String, Int32, Int32, Texture2D&)
> MOOB.Patches.TerrainPanelSystem_ShowImportHeightmapPanelPatch:Prefix(TerrainPanelSystem&)
> Game.UI.Editor.TerrainPanelSystem:DMD<Game.UI.Editor.TerrainPanelSystem::ShowImportHeightmapPanel>(TerrainPanelSystem)
> Game.UI.Widgets.Button:Invoke()
> Game.UI.Widgets.<>c:<CreateBindings>b__0_0(IWidget)
> Colossal.UI.Binding.TriggerBinding`1:Callback()
> System.Reflection.RuntimeMethodInfo:InternalInvoke(RuntimeMethodInfo, Object, Object[], Exception&)
> System.Reflection.RuntimeMethodInfo:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
> System.Reflection.MethodBase:Invoke(Object, Object[])
> cohtml.Net.Invoker:ExecuteAndSendResult(Binder, Delegate, Object[], Boolean)
> cohtml.Net.Invoker:Invoke(Int32)
> cohtml.Net.cohtmlNativePINVOKE:View_MouseEvent(HandleRef, HandleRef)
> cohtml.Net.View:MouseEvent(IMouseEventData)
> Colossal.UI.UIInputSystem:DispatchInputEvents(UIView, Boolean, InputEventType)
> Colossal.UI.UIInputSystem:DispatchInputEvents()
> Game.SceneFlow.GameManager:Update()

Yet the message does not specify the dimensions.
Does the width and height need to be something specific? Does the size of the file need to be something specific? I have no idea what to make of the error message.

**Comment by shssoichiro** [comment]
What I've figured out so far is the heightmap needs to be 4096x4096 in 16-bit RAW format. I've been working on changes to skydark's generator to support this, and although I've gotten heightmaps that appear to [generate correctly](https://i.slow.pics/3X0MXKAw.png) and import successfully, the result when imported into the game looks quite [cursed.](https://i.slow.pics/N2x0xuKW.png) I'm wondering if the math for determining height vectors has also changed from CS1, though I'm not sure how to find the new expected math.

**Comment by optimus-code** [comment]
Are you able to share the source heightmap in raw format?

**Comment by WatchfulRelic91** [comment]
> Are you able to share the source heightmap in raw format?

No. Apparently GitHub does not support the RAW file format. I retrieved it from https://heightmap.skydark.pl/ though, and tried multiple locations and sizes.

**Comment by SadFrogger** [comment]
> What I've figured out so far is the heightmap needs to be 4096x4096 in 16-bit RAW format. I've been working on changes to skydark's generator to support this, and although I've gotten heightmaps that appear to [generate correctly](https://i.slow.pics/3X0MXKAw.png) and import successfully, the result when imported into the game looks quite [cursed.](https://i.slow.pics/N2x0xuKW.png) I'm wondering if the math for determining height vectors has also changed from CS1, though I'm not sure how to find the new expected math.

I've spent the past couple hours trying to figure something out with this, I tried a couple different options for getting the heightmap from skydark's generator to load into the game. 
First tried to rescale using Camera Raw on Photoshop but that wouldn't properly import, same error as OP
Then tried to export a file, and overlay the desired heightmap on that, but that wouldn't properly import
Thirdly tried to write a script that converts the 1081x1081 8Bit raw heightmap into and 4096x4096 16bit raw heightmap and it made something that you could import into the game, but it completely jumbled the data from the original heightmap.
Are you able to send whatever it is that you used so I could have a look at it?

**Comment by shssoichiro** [comment]
Yes, I pushed my skydark changes to a fork [here](https://github.com/shssoichiro/Cities-Skylines-heightmap-generator/tree/changes) (see the "changes" branch), you can run this locally from your machine without any node shenanigans just by navigating to the index.html file. This is how I generated the heatmap I linked previously (the grayscale version is the PNG export, CS2 will only accept the RAW export however).

**Comment by shssoichiro** [comment]
I've made some improvements--the water outlines now actually look like water outlines--however there's still some sort of issue with the height maps where they're not matching the new expected resolution. I'm continuing to work through this, I have no familiarity with the mapbox API but I'll update when/if I figure it out. I'd love to have working CS2 imports soon.

**Comment by shssoichiro** [comment]
Good news, I've gotten the fork to generate accurate RAW maps for CS2. There were a lot of really strange and annoying things that had to be changed. For example, CS2 imports heightmaps upside-down... so it had to be flipped vertically.


<img width="1346" alt="importsuccess" src="https://github.com/Cities2Modding/MOOB/assets/5951392/ec6397e5-6de5-4c72-954c-201b5b9b8c87">

There is however still an issue where the gradients of slopes are not smooth. You can see contour lines on the imported terrain especially on mountains and shorelines. It's unfortunate, but I believe this is a limitation of the game. The CS2 devs (or some very adventurous modder) will need to implement terrain smoothing on heightmap import, there's nothing heightmap generation can do to resolve this.


<img width="688" alt="terraingradients" src="https://github.com/Cities2Modding/MOOB/assets/5951392/83304bfa-b1b0-46c8-ad57-09a3b87cf1eb">

**Comment by ZooHuba** [comment]
None of that works

**Comment by ZooHuba** [comment]
Nothing in the mod works. Select load heightmap on editor and nothing happens.

**Comment by RtxLive** [comment]
@shssoichiro
When i open the heightmap generator through the index.html file, all the buttons except the download buttons work

**Comment by optimus-code** [comment]
Importing heightmaps is no longer current MOOB functionality. Any issues with this are game related and liable to be fixed with official game updates soon.
