### ISSUE TITLE
no sea after loading a map save

### ISSUE THREAD

**Issue by royjah** [Cities2Modding/MOOB#4]
Hi,

It's my first time that I report an issue on Github, so excuse me if i'm doing wrong ^^

I'm trying to import a heigtmap on Cities Skylines 2, in the first place it work well. But when I save the map, then load it, the water don't spawn in the tiles but only around. So I tried to re import an other heightmap, and the water is still not here. I'm also new about creating map, so maybe I'm just missing something.

Thank you for your reply and for the work on mod :)
and sorry for my poor english ^^

![Capture](https://github.com/Cities2Modding/MOOB/assets/151786359/7240de8d-e6fd-42fe-b2da-6c2c599e0ca3)

**Comment by txoba** [comment]
Same here, if you find a way to solve it, please post it

**Comment by muItilingualism** [comment]
This guide by dtoxftw may help you https://cities2modding.github.io/wiki/guides/map-editor.html
