### ISSUE TITLE
Expanding on water issue & terrain height

### ISSUE THREAD

**Issue by Kalcipher** [Cities2Modding/MOOB#6]
If CS2 water physics are still bugged then I understand there will not be good correlation between editor save and a new game on that map... however, the addition of an X,Y cursor tracker would be stellar!!

I'm just having trouble with placing and setting water heights & getting it to load correctly in game. Instructions on how may units X & Y the playable map is and the non-playable map would help when placing water sources on a grid system. Also my playable map water levels are not matching the edge map water levels... for example, if i set playable map water level to 65 and the same for edge map water level, when i open it in a new game the edge map water level is higher than my land... not sure what the multipliers are there but i'm not smart enough to figure that stuff out without extensive trial & error.

i'll try to attach a picture of a map made in editor, loaded as a new game...

![Screenshot (97)](https://github.com/Cities2Modding/MOOB/assets/29763675/65d15f4c-1525-46fd-8ff5-1354646352ae)

**Comment by optimus-code** [comment]
Importing heightmaps is no longer current MOOB functionality. Any issues with this are game related and liable to be fixed with official game updates soon.
