### ISSUE TITLE
Can't save any map on the editor. 

### ISSUE THREAD

**Issue by Turbobite** [Cities2Modding/MOOB#9]
Nothing happens when I click the buttons. There's no option in the menu either.

![image](https://github.com/Cities2Modding/MOOB/assets/153123168/b6354bcc-ff2c-42bd-bb68-32669ca52b6d)

**Comment by Turbobite** [comment]
Also I can't find the maps in my saved games or by starting a new game

**Comment by optimus-code** [comment]
MOOB doesn't control this functionality and in light of incoming updates we are not liable to try fix game bugs.
